Repository RAF-SI-2023/Banka-1-Frontend, pull requests merged in 2024-05, with the labels that each got.

#155 BankAccounts and Cards Components
  src/app/app.routes.ts
  src/app/bank-accounts-and-cards/bank-accounts-and-cards.component.css
  src/app/bank-accounts-and-cards/bank-accounts-and-cards.component.html
  src/app/bank-accounts-and-cards/bank-accounts-and-cards.component.spec.ts
  src/app/bank-accounts-and-cards/bank-accounts-and-cards.component.ts
  src/app/bank-accounts/bank-accounts.component.css
  src/app/bank-accounts/bank-accounts.component.html
  src/app/bank-accounts/bank-accounts.component.spec.ts
  src/app/bank-accounts/bank-accounts.component.ts
  src/app/cards/cards.component.css
  src/app/cards/cards.component.html
  src/app/cards/cards.component.spec.ts
  src/app/cards/cards.component.ts
Labels: approved, size/XXL, lgtm

#157 Cursor fix
  src/app/bank-accounts-and-cards/bank-accounts-and-cards.component.css
Labels: approved, size/XS, lgtm

#160 Add dropdown cursor type
  src/app/welcome/redesign/DropdownInput.ts
Labels: approved, size/XS, lgtm

#164 Sprint 5
  src/app/app.routes.ts
Labels: ¯\_(ツ)_/¯, approved, size/XS, lgtm

#162 Sprint 5 additional ticket
  src/app/new-payment/new-payment.component.css
  src/app/new-payment/new-payment.component.html
  src/app/new-payment/new-payment.component.ts
  src/app/transaction/transaction.component.html
  src/app/transaction/transaction.component.ts
Labels: size/M, approved, lgtm

#163 PROW
  .prow/deploy.yaml
Labels: size/M, approved, lgtm

#168 Delete .prow/deploy.yaml
  .prow/deploy.yaml
Labels: approved, lgtm

#175 Added docker for frontend
  .prow/deploy.yaml
  Dockerfile
  angular.json
Labels: size/M, approved, lgtm

#179 AdminBankDetails
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.routes.ts
  src/app/bank-account-admin/bank-account-admin.component.css
  src/app/bank-account-admin/bank-account-admin.component.html
  src/app/bank-account-admin/bank-account-admin.component.spec.ts
  src/app/bank-account-admin/bank-account-admin.component.ts
  src/app/bank-profit/bank-profit.component.css
  src/app/bank-profit/bank-profit.component.html
  src/app/bank-profit/bank-profit.component.spec.ts
  src/app/bank-profit/bank-profit.component.ts
  src/app/model/model.ts
  src/app/service/bank-account.service.ts
  src/app/service/profit.service.spec.ts
  src/app/service/profit.service.ts
  src/app/transaction-details-admin/transaction-details-admin.component.css
  src/app/transaction-details-admin/transaction-details-admin.component.html
  src/app/transaction-details-admin/transaction-details-admin.component.spec.ts
  src/app/transaction-details-admin/transaction-details-admin.component.ts
Labels: approved, size/XXL, lgtm

#181 Sprint 5
  angular.json
  src/app/service/profit.service.ts
Labels: approved, size/XS, lgtm

#182 FE DevOps
  Dockerfile
  docker-compose.yaml
  nginx.conf
Labels: size/M, approved, lgtm

#184 OTC admin
  src/app/app.component.html
  src/app/app.routes.ts
  src/app/model/model.ts
  src/app/otc/otc.component.css
  src/app/otc/otc.component.html
  src/app/otc/otc.component.spec.ts
  src/app/otc/otc.component.ts
  src/app/service/otc.service.spec.ts
  src/app/service/otc.service.ts
  src/app/welcome/redesign/TableComponent.ts
  src/assets/mocked_banking_data/contracts-mocked.json
  src/assets/mocked_banking_data/otc-mocked.json
  src/assets/mocked_banking_data/stocks-mocked.json
Labels: size/XL, approved, lgtm

#186 Sprint 5
  src/app/app.component.html
  src/app/welcome/redesign/TableComponent.ts
Labels: size/M, approved, lgtm

#185 Order public securities
  src/app/add-user/add-user.component.css
  src/app/list-user/list-user.component.html
  src/app/orders/TransformPublicSecuritiesPipe.ts
  src/app/orders/TransformSecuritiesPipe.ts
  src/app/orders/orders.component.css
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.css
  src/app/public-security-offer-popup/public-security-offer-popup.component.html
  src/app/public-security-offer-popup/public-security-offer-popup.component.spec.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.ts
  src/app/service/bank-account.service.ts
  src/app/service/order.service.ts
  src/app/service/popup.service.ts
Labels: size/XL, approved, lgtm

#188 Sprint 5
  src/app/app.component.html
  src/app/otc/otc.component.html
  src/app/service/otc.service.ts
  src/app/welcome/redesign/TableComponent.ts
Labels: size/M, approved, lgtm

#180 Mini fix
  angular.json
Labels: approved, size/XS, lgtm

#189 Sprint 5
  src/app/app.component.html
Labels: approved, size/XS, lgtm

#194 Sprint 5
  src/app/login-page/login-page.component.html
  src/app/model/model.ts
  src/app/otc/otc.component.css
  src/app/otc/otc.component.html
  src/app/otc/otc.component.ts
  src/app/welcome/redesign/LineTextField.ts
  src/app/welcome/redesign/TransparentTextField.ts
  src/assets/mocked_banking_data/active-sell.json
  src/assets/mocked_banking_data/public-offers.json
Labels: approved, size/L, lgtm

#183 Legal persons page, add legal person pop up, join customer and legal person pop up
  environment.ts
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.css
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.html
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.spec.ts
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.ts
  src/app/app.component.html
  src/app/app.routes.ts
  src/app/customer/customer.component.ts
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.css
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.html
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.spec.ts
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.ts
  src/app/legal-persons/legal-persons.component.css
  src/app/legal-persons/legal-persons.component.html
  src/app/legal-persons/legal-persons.component.spec.ts
  src/app/legal-persons/legal-persons.component.ts
  src/app/model/model.ts
  src/app/new-payment/new-payment.component.html
  src/app/service/legal-person.service.spec.ts
  src/app/service/legal-person.service.ts
  src/app/service/popup.service.ts
  src/assets/mocked_banking_data/mocked_legal_persons.json
Labels: approved, size/XXL, lgtm

#193 Production configuration
  .prow/frontend.yaml
  angular.json
  environment.ts
  package-lock.json
  package.json
  playwright/playwright.config.ts
  playwright/tests/agent_supervisor_scenario.spec.ts
  playwright/tests/change_limit.spec.ts
  playwright/tests/create_order.spec.ts
  playwright/tests/create_payment.spec.ts
  playwright/tests/create_recipient.spec.ts
  playwright/tests/edit_user.spec.ts
  playwright/tests/payment.spec.ts
  playwright/tests/removeuser.spec.ts
  playwright/tests/test-1.spec.ts
  playwright/tests/test-2.spec.ts
  src/app/exchange-rate/exchange-rate.component.ts
  src/app/legal-persons/legal-persons.component.ts
  src/app/loans/new-loan/new-loan.component.ts
  src/app/reset-password/reset-password.component.ts
  src/app/security-list/components/forex-table/forex-table.component.ts
  src/app/security-list/components/future-table/future-table.component.ts
  src/app/security-list/security-list.component.ts
  src/app/service/account.service.ts
  src/app/service/auth.service.ts
  src/app/service/bank-account.service.ts
  src/app/service/card.service.ts
  src/app/service/customer.service.ts
  src/app/service/employee.service.ts
  src/app/service/forex.service.ts
  src/app/service/future.service.ts
  src/app/service/legal-person.service.ts
  src/app/service/order.service.ts
  src/app/service/otc.service.ts
  src/app/service/payment.service.ts
  src/app/service/permission.service.ts
  src/app/service/permissions.service.ts
  src/app/service/profit.service.ts
  src/app/service/stock.service.ts
  src/app/service/transaction.service.ts
  src/app/set-password/set-password.component.ts
  src/app/user-reset-password/user-reset-password.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  test-results/.last-run.json
Labels: approved, size/XXL, lgtm

#199 Merge
  src/environments/environment.prod.ts
Labels: approved, size/XS, lgtm
