Repository RAF-SI-2023/Banka-1-Frontend, pull requests merged in 2024-06, with the labels that each got.

#201 Sprint5 rebase
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/bank-profit/bank-profit.component.ts
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.ts
  src/app/legal-persons/legal-persons.component.html
  src/app/login-page/login-page.component.html
  src/app/security-list/security-list.component.ts
  src/app/service/legal-person.service.ts
  src/environments/environment.ts
Labels: approved, size/L, lgtm

#202 update deploy.yaml
  .prow/deploy.yaml
Labels: size/XS

#207 Sprint5 rebase
  src/app/app.component.html
  src/app/model/model.ts
  src/app/orders/orders.component.ts
  src/app/otc-customer/otc-customer.component.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.ts
  src/app/service/bank-account.service.ts
  src/app/service/order.service.ts
Labels: approved, size/L, lgtm

#206 Sprint bugs tickets resolved
  environment.ts
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.html
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.ts
  src/app/add-user/add-user.component.ts
  src/app/app.component.html
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.ts
  src/app/legal-persons/legal-persons.component.html
  src/app/legal-persons/legal-persons.component.ts
  src/app/list-user/list-user.component.html
  src/app/model/model.ts
  src/app/permissions-popup/permission-pop-up/permission-pop-up.component.html
  src/app/permissions-popup/permission-pop-up/permission-pop-up.component.ts
  src/app/service/legal-person.service.ts
Labels: approved, size/L, lgtm

#208 Sprint5 rebase
  src/app/orders/orders.component.ts
  src/app/otc-customer/otc-customer.component.html
  src/app/otc-customer/otc-customer.component.ts
  src/app/service/bank-account.service.ts
Labels: approved, size/L, lgtm

#211 Sprint5 rebase
  src/app/orders/orders.component.ts
  src/app/otc-customer/otc-customer.component.ts
Labels: approved, size/XS, lgtm

#212 Sprint5 rebase
  src/app/otc-customer/otc-customer.component.ts
Labels: approved, size/L, lgtm

#214 Sprint5 rebase
  src/app/orders/TransformPublicSecuritiesPipe.ts
  src/app/orders/TransformSecuritiesPipe.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/otc-customer/otc-customer.component.html
  src/app/otc-customer/otc-customer.component.ts
  src/app/otc/otc.component.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.ts
  src/app/service/order.service.ts
Labels: size/M, approved, lgtm

#213 Fix
  src/app/model/model.ts
  src/app/otc-customer/otc-customer.component.ts
  src/app/service/order.service.ts
Labels: approved, size/L, lgtm

#215 fix bugs that prevent testing
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.ts
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.html
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.ts
  src/app/legal-persons/legal-persons.component.ts
  src/app/service/legal-person.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: size/M, approved, lgtm

#217 Sprint5 rebase
  src/app/otc-customer/TransformContractsPipe.ts
  src/app/otc-customer/TransformStatusPipe.ts
  src/app/otc-customer/otc-customer.component.html
  src/app/otc-customer/otc-customer.component.ts
  src/app/otc/otc.component.html
  src/app/otc/otc.component.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.ts
  src/app/service/bank-account.service.ts
  src/app/service/otc.service.ts
  src/app/service/stock.service.ts
Labels: approved, size/L, lgtm

#218 Sprint5 rebase
  src/app/service/otc.service.ts
Labels: approved, lgtm, size/S

#219 Update deploy.yaml
  .prow/deploy.yaml
Labels: approved, size/XS, lgtm

#220 restore securities page
  src/app/app.component.html
  src/app/app.routes.ts
  src/app/forex-view/forex-view.component.ts
  src/app/future-view/future-view.component.ts
  src/app/stock-view/stock-view.component.ts
Labels: approved, lgtm, size/S

#221 Environment changes
  .prow/deploy.yaml
  Dockerfile
  angular.json
  package.json
  src/environments/environment.dev.ts
  src/environments/environment.prod.ts
Labels: size/M, approved, lgtm

#222 Helm
  .prow/deploy.yaml
Labels: approved, size/XS, lgtm

#224 Fix
  package-lock.json
  src/app/app.component.html
  src/app/app.routes.ts
  src/app/orders-legal-persons/orders-legal-persons.component.html
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/TransformPublicSecuritiesPipe.ts
  src/app/orders/TransformSecuritiesPipe.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.ts
  src/app/securities-legal-persons/securities-legal-persons.component.ts
  src/app/security-list/security-list.component.html
  src/app/security-list/security-list.component.ts
  src/app/service/bank-account.service.ts
  src/app/service/options.service.ts
  src/app/service/order.service.ts
  src/app/service/stock.service.ts
  src/app/stock-view/stock-view.component.ts
  src/app/transform-forex.pipe.ts
Labels: approved, size/XXL, lgtm

#226 Fixes
  src/app/securities-legal-persons/securities-legal-persons.component.html
  src/app/security-list/security-list.component.html
  src/app/transform-future.pipe.ts
  src/app/transform-security.pipe.ts
Labels: size/M, approved, lgtm

#227 change visible navbar elements for customer and legal person
  src/app/app.component.html
  src/app/app.routes.ts
  src/app/security-list/security-list.component.html
Labels: approved, lgtm, size/S

#216 Fixovi za edit i add customera
  src/app/add-bank-account/add-bank-account.component.ts
  src/app/edit-customer/edit-customer.component.html
  src/app/edit-customer/edit-customer.component.ts
  src/app/exchange-rate/exchange-rate.component.ts
  src/app/otc-customer/otc-customer.component.ts
  src/app/otc/otc.component.ts
  src/app/pop-up-with-refresh/pop-up-with-refresh.component.css
  src/app/pop-up-with-refresh/pop-up-with-refresh.component.html
  src/app/pop-up-with-refresh/pop-up-with-refresh.component.spec.ts
  src/app/pop-up-with-refresh/pop-up-with-refresh.component.ts
  src/app/service/exchange.service.spec.ts
  src/app/service/exchange.service.ts
  src/app/service/popup.service.ts
  src/app/service/transaction.service.ts
  src/app/transaction-popup/transaction-popup.component.ts
  src/app/welcome/redesign/DropdownInput.ts
Labels: approved, size/L, lgtm

#223 Lead-ovi prevaranti
  environment.ts
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.html
  src/app/add-new-legal-person-pop-up/add-new-legal-person-pop-up.component.ts
  src/app/app.component.html
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.ts
  src/app/legal-persons/legal-persons.component.html
  src/app/legal-persons/legal-persons.component.ts
  src/app/model/model.ts
  src/app/service/legal-person.service.ts
Labels: approved, size/L, lgtm

#230 Margin, Profit i OTC (admin)
  src/app/app.routes.ts
  src/app/bank-profit/bank-profit.component.ts
  src/app/margin-call-pop-up/margin-call-pop-up.component.html
  src/app/margin-call-pop-up/margin-call-pop-up.component.ts
  src/app/margin-transaction-details/margin-transaction-details.component.html
  src/app/margin-transaction-details/margin-transaction-details.component.ts
  src/app/margin/margin.component.html
  src/app/margin/margin.component.ts
  src/app/model/model.ts
  src/app/otc-customer/TransformStatusPipe.ts
  src/app/otc/otc.component.html
  src/app/otc/otc.component.ts
  src/app/service/margin.service.ts
  src/app/service/otc.service.ts
  src/app/service/profit.service.ts
  src/app/transform-margin-accounts.pipe.spec.ts
  src/app/transform-margin-accounts.pipe.ts
  src/app/transform-margin-details.pipe.spec.ts
  src/app/transform-margin-details.pipe.ts
  src/app/welcome/redesign/DropDownInputStatus.ts
Labels: size/XL, approved, lgtm

#232 Sprint5 rebase
  src/app/otc-customer/TransformStatusPipe.ts
  src/app/otc-customer/otc-customer.component.html
  src/app/otc/otc.component.html
  src/app/service/otc.service.ts
Labels: size/M, approved, lgtm

#231 Legal persons filter
  src/app/legal-persons/legal-persons.component.css
  src/app/legal-persons/legal-persons.component.html
  src/app/legal-persons/legal-persons.component.ts
Labels: approved, size/L, lgtm

#233 Add isMargin field in buy request
  src/app/model/model.ts
  src/app/service/order.service.ts
Labels: approved, size/XS, lgtm

#234 Fixes in frontend
  src/app/app.component.html
  src/app/sell-popup/sell-popup.component.ts
Labels: approved, lgtm, size/S

#235 remove redundant status column in table
  src/app/orders/orders.component.html
Labels: approved, size/XS, lgtm

#237 OTC customer on sprint-5
  src/app/orders/TransformPublicSecuritiesPipe.ts
  src/app/otc-customer/otc-customer.component.html
  src/app/otc-customer/otc-customer.component.ts
  src/app/otc/otc.component.html
  src/app/otc/otc.component.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.ts
  src/app/service/otc.service.ts
Labels: approved, size/L, lgtm

#236 Refresh dugme za Securities
  src/app/bank-profit/bank-profit.component.css
  src/app/bank-profit/bank-profit.component.html
  src/app/bank-profit/bank-profit.component.ts
  src/app/otc-customer/TransformStatusPipe.ts
  src/app/otc/otc.component.html
  src/app/otc/otc.component.ts
  src/app/securities-legal-persons/securities-legal-persons.component.ts
  src/app/security-list/security-list.component.css
  src/app/security-list/security-list.component.html
  src/app/security-list/security-list.component.ts
  src/app/service/forex.service.ts
  src/app/service/future.service.ts
  src/assets/refresh.png
Labels: size/XL, approved, lgtm

#238 Sprint 5 otc
  src/app/otc-customer/TransformStatusPipe.ts
  src/app/otc/otc.component.html
  src/app/otc/otc.component.ts
  src/app/welcome/redesign/DropDownInputStatus.ts
Labels: approved, size/L, lgtm

#239 Sprint 5 otc
  src/app/otc-customer/otc-customer.component.html
  src/app/otc-customer/otc-customer.component.ts
  src/app/otc/otc.component.ts
  src/app/service/bank-account.service.ts
Labels: approved, size/L, lgtm

#240 Public Securities for legal persons
  src/app/model/model.ts
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/orders.component.ts
  src/app/sell-popup/sell-popup.component.ts
  src/app/service/order.service.ts
  src/app/service/popup.service.ts
Labels: approved, size/L, lgtm

#242 Sprint fixed bugs
  src/app/add-user/add-user.component.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/list-user/list-user.component.html
  src/app/list-user/list-user.component.ts
  src/app/login-page/login-page.component.ts
  src/app/model/model.ts
  src/app/service/popup.service.ts
  src/app/successfully-created-user/successfully-created-user.component.css
  src/app/successfully-created-user/successfully-created-user.component.html
  src/app/successfully-created-user/successfully-created-user.component.spec.ts
  src/app/successfully-created-user/successfully-created-user.component.ts
Labels: approved, size/L, lgtm

#243 Sprint 5 otc
  src/app/model/model.ts
  src/app/otc-customer/otc-customer.component.ts
Labels: size/M, approved, lgtm

#244 Sprint 5 otc
  src/app/otc-customer/otc-customer.component.ts
  src/app/service/order.service.ts
Labels: approved, lgtm, size/S

#246 Sprint 5 otc
  src/app/otc-customer/TransformContractsHistoryPipe.ts
  src/app/otc-customer/TransformContractsPipe.ts
  src/app/otc-customer/otc-customer.component.ts
  src/app/welcome/redesign/DateUtils.ts
Labels: size/M, approved, lgtm

#248 Transaction details
  src/app/service/transaction.service.ts
  src/app/transform-bank-account-details.pipe.ts
  src/assets/ newtransaction.json
Labels: approved, size/L, lgtm

#247 Legal person label
  src/app/app.component.html
  src/app/app.component.ts
Labels: approved, lgtm, size/S

#250 Zavrsen Margin
  src/app/otc-customer/TransformStatusPipe.ts
  src/app/otc/otc.component.html
  src/app/otc/otc.component.ts
Labels: size/M, approved, lgtm

#249 Fix
  src/app/app.component.ts
  src/app/buy-stock-popup/buy-stock-popup.component.html
  src/app/buy-stock-popup/buy-stock-popup.component.ts
  src/app/login-page/login-page.component.ts
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/orders.component.ts
  src/app/sell-popup/sell-popup.component.ts
  src/app/service/order.service.ts
  src/app/service/popup.service.ts
Labels: approved, size/L, lgtm

#253 Update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm

#252 Margin
  src/app/buy-stock-popup/buy-stock-popup.component.css
  src/app/buy-stock-popup/buy-stock-popup.component.html
  src/app/buy-stock-popup/buy-stock-popup.component.ts
  src/app/securities-legal-persons/securities-legal-persons.component.html
  src/app/securities-legal-persons/securities-legal-persons.component.ts
  src/app/service/order.service.ts
  src/app/service/popup.service.ts
Labels: approved, size/L, lgtm

#254 Popravljen Margin
  src/app/buy-stock-popup/buy-stock-popup.component.ts
  src/app/service/order.service.ts
Labels: size/M, approved, lgtm

#257 Sprint 5 otc
  src/app/model/model.ts
  src/app/otc-customer/otc-customer.component.ts
  src/app/otc/otc.component.ts
Labels: approved, lgtm, size/S

#259 Sprint 5 otc
  src/app/otc-customer/TransformContractsHistoryPipe.ts
  src/app/otc-customer/TransformContractsPipe.ts
  src/app/otc-customer/otc-customer.component.ts
  src/app/otc/otc.component.ts
  src/app/public-security-offer-popup/public-security-offer-popup.component.html
  src/app/public-security-offer-popup/public-security-offer-popup.component.ts
Labels: size/M, approved, lgtm

#256 Company added to legal person label
  src/app/app.component.html
  src/app/app.component.ts
  src/app/login-page/login-page.component.ts
  src/app/model/model.ts
Labels: approved, size/XS, lgtm

#258 Orders page tabs fixed
  src/app/buy-stock-popup/buy-stock-popup.component.html
  src/app/orders-legal-persons/orders-legal-persons.component.html
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/service/order.service.ts
Labels: approved, size/L, lgtm

#262 PopUp and liitle enu functionality for multi OTC done
  src/app/model/model.ts
  src/app/otc-multi/otc-multi.component.html
  src/app/otc-multi/otc-multi.component.ts
  src/app/sell-multi-otc-pop-up/sell-multi-otc-pop-up.component.css
  src/app/sell-multi-otc-pop-up/sell-multi-otc-pop-up.component.html
  src/app/sell-multi-otc-pop-up/sell-multi-otc-pop-up.component.ts
  src/app/service/multi-otc.service.ts
  src/app/service/popup.service.ts
Labels: approved, size/L, lgtm

#263 Sprint 5
  src/app/model/model.ts
  src/app/orders/orders.component.ts
Labels: approved, lgtm, size/S

#265 Final
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/join-legal-person-and-customer-pop-up/join-legal-person-and-customer-pop-up.component.ts
  src/app/margin-call-pop-up/margin-call-pop-up.component.html
  src/app/margin-call-pop-up/margin-call-pop-up.component.ts
  src/app/margin/margin.component.ts
  src/app/model/model.ts
  src/app/service/margin.service.ts
Labels: approved, size/L, lgtm

#267 Orders za fizicka i pravna lica
  src/app/app.component.html
  src/app/orders-legal-persons/orders-legal-persons.component.html
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/securities-legal-persons/securities-legal-persons.component.ts
  src/app/security-list/security-list.component.html
  src/app/security-list/security-list.component.ts
  src/app/stock-view/stock-view.component.ts
  src/app/transform-order-history.pipe.spec.ts
  src/app/transform-order-history.pipe.ts
Labels: approved, size/L, lgtm

#268 Fix
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
Labels: approved, size/L, lgtm

#269 sprint 5
  src/app/app.component.html
  src/app/orders/orders.component.ts
Labels: approved, lgtm, size/S

#270 Final
  src/app/app.component.html
  src/app/exchange-transaction-report/exchange-transaction-report.component.ts
  src/app/model/model.ts
  src/app/service/exchange-transaction-report.service.ts
Labels: size/M, approved, lgtm
