Repository RAF-SI-2023/Banka-1-Frontend, pull requests merged in 2024-04, with the labels that each got.

#98 Sprint 4 redesign 1
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/app/login-page/login-page.component.css
  src/app/login-page/login-page.component.html
  src/app/login-page/login-page.component.ts
  src/app/welcome/redesign/LineTextField.ts
  src/app/welcome/redesign/OrangeButton.ts
  src/app/welcome/redesign/TransparentTextField.ts
  src/app/welcome/redesign/WhiteTextField.ts
  src/app/welcome/welcome.component.css
  src/app/welcome/welcome.component.html
  src/app/welcome/welcome.component.ts
  src/assets/expand.png
  src/assets/pozadina_dark.png
  src/styles.css
Labels: size/XL

#97 fix some css annd connect form to new loan component
  src/app/loans/loan-details/loan-details.component.css
  src/app/loans/loan-details/loan-details.component.html
  src/app/loans/loan-table/loan-table.component.css
  src/app/loans/loan-table/loan-table.component.ts
  src/app/loans/new-loan/new-loan.component.css
  src/app/loans/new-loan/new-loan.component.html
  src/app/loans/new-loan/new-loan.component.ts
Labels: size/M, lgtm

#92 Orders
  src/app/app.component.html
  src/app/app.routes.ts
  src/app/model/model.ts
  src/app/orders/orders.component.css
  src/app/orders/orders.component.html
  src/app/orders/orders.component.spec.ts
  src/app/orders/orders.component.ts
  src/app/service/order.service.spec.ts
  src/app/service/order.service.ts
  src/assets/orderHistory.json
  src/assets/orderRequests.json
  src/assets/orderSecurities.json
  src/assets/x.svg
Labels: size/XL

#101 Sprint 4
  src/app/activate-account/activate-account.component.css
  src/app/activate-account/activate-account.component.html
  src/app/activate-account/activate-account.component.ts
  src/app/reset-password/reset-password.component.css
  src/app/reset-password/reset-password.component.html
  src/app/reset-password/reset-password.component.ts
  src/app/set-password/set-password.component.css
  src/app/set-password/set-password.component.html
  src/app/set-password/set-password.component.ts
  src/app/user-reset-password/user-reset-password.component.css
  src/app/user-reset-password/user-reset-password.component.html
  src/app/user-reset-password/user-reset-password.component.ts
Labels: size/XXL

#113 Limit i available u Orderes
  src/app/add-customer/add-customer.component.html
  src/app/buy-popup/buy-popup.component.css
  src/app/buy-popup/buy-popup.component.html
  src/app/buy-popup/buy-popup.component.spec.ts
  src/app/buy-popup/buy-popup.component.ts
  src/app/list-user/TransformLimitsPipe.ts
  src/app/list-user/list-user.component.html
  src/app/list-user/list-user.component.ts
  src/app/model/model.ts
  src/app/orders/orders.component.css
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/service/account.service.ts
  src/app/service/employee.service.ts
  src/app/service/order.service.ts
  src/app/service/popup.service.ts
  src/app/welcome/redesign/TableComponent.ts
  src/app/welcome/redesign/WhiteTextField.ts
  src/assets/mocked_banking_data/mocked_limits/limits-mocked.json
Labels: size/XL

#114 sprint 5
  src/app/bank-accounts/bank-accounts.component.css
  src/app/bank-accounts/bank-accounts.component.html
  src/app/card-transactions/card-transactions.component.css
  src/app/customer/customer.component.css
  src/app/list-user/list-user.component.css
  src/app/model/model.ts
  src/app/new-payment/new-payment.component.html
  src/app/new-payment/new-payment.component.ts
  src/app/orders/orders.component.css
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/recipients/recipients.component.html
  src/app/security-list/security-list.component.css
  src/app/service/order.service.ts
  src/assets/orderHistory.json
  src/assets/orderRequests.json
  src/assets/orderSecurities.json
Labels: needs-rebase, size/L

#117 Redizajn Exchange-rate stranice
  src/app/exchange-rate/exchange-rate.component.css
  src/app/exchange-rate/exchange-rate.component.html
  src/app/exchange-rate/exchange-rate.component.ts
  src/app/model/forex-filter-pipe.pipe.ts
  src/app/model/model.ts
  src/app/welcome/redesign/TableComponent.ts
Labels: size/L

#118 Bank accounts and cards of customer for admin view redesign
  src/app/customer/customer.component.ts
  src/app/user-detail/user-detail.component.css
  src/app/user-detail/user-detail.component.html
  src/app/user-detail/user-detail.component.ts
  src/app/welcome/redesign/TableComponent.ts
Labels: size/L

#123 Sredjen dizajn popup-ova :)
  src/app/add-bank-account/add-bank-account.component.css
  src/app/add-bank-account/add-bank-account.component.html
  src/app/add-customer/add-customer.component.css
  src/app/add-customer/add-customer.component.html
  src/app/add-user/add-user.component.css
  src/app/add-user/add-user.component.html
  src/app/list-user/list-user.component.css
  src/app/list-user/list-user.component.html
  src/app/update-user/update-user.component.css
  src/app/update-user/update-user.component.html
Labels: size/XXL

#124 PR
  src/app/activate-account/activate-account.component.css
  src/app/activate-account/activate-account.component.html
  src/app/activate-account/activate-account.component.ts
  src/app/buy-popup/buy-popup.component.html
  src/app/buy-popup/buy-popup.component.ts
  src/app/customer/customer.component.html
  src/app/forex-view/forex-view.component.html
  src/app/forex-view/forex-view.component.ts
  src/app/future-view/future-view.component.html
  src/app/future-view/future-view.component.ts
  src/app/list-user/list-user.component.css
  src/app/list-user/list-user.component.html
  src/app/list-user/list-user.component.ts
  src/app/orders/orders.component.css
  src/app/orders/orders.component.ts
  src/app/popup/popup.component.css
  src/app/service/order.service.ts
  src/app/welcome/redesign/TransparentTextField.ts
  src/app/welcome/welcome.component.html
Labels: size/L

#126 Sprint 5
  src/app/app.component.html
  src/app/forex-view/forex-view.component.css
  src/app/forex-view/forex-view.component.html
  src/app/forex-view/forex-view.component.ts
  src/app/future-view/future-view.component.css
  src/app/future-view/future-view.component.html
  src/app/future-view/future-view.component.ts
  src/app/security-list/security-list.component.css
  src/app/security-list/security-list.component.html
  src/app/service/forex.service.ts
  src/app/service/stock.service.ts
  src/app/stock-view/stock-view.component.css
  src/app/stock-view/stock-view.component.html
  src/app/stock-view/stock-view.component.ts
  src/app/transform-security.pipe.ts
  src/assets/futures-mock.json
Labels: size/XXL

#125 Buy popup integrated into forex and future in securities, orders limi…
  src/app/buy-popup/buy-popup.component.css
  src/app/buy-popup/buy-popup.component.html
  src/app/buy-popup/buy-popup.component.ts
  src/app/forex-view/forex-view.component.ts
  src/app/future-view/future-view.component.ts
  src/app/model/model.ts
  src/app/orders/orders.component.ts
  src/app/popup/popup.component.html
  src/app/service/order.service.ts
  src/app/service/popup.service.ts
  src/app/welcome/redesign/WhiteTextField.ts
Labels: size/L

#128 sprint-5 fixed
  src/app/delete-recipient-confirmation/delete-recipient-confirmation.component.css
  src/app/delete-recipient-confirmation/delete-recipient-confirmation.component.html
  src/app/delete-recipient-confirmation/delete-recipient-confirmation.component.spec.ts
  src/app/delete-recipient-confirmation/delete-recipient-confirmation.component.ts
  src/app/edit-recipient/edit-recipient.component.ts
  src/app/new-recipient/new-recipient.component.ts
  src/app/recipients/recipients.component.ts
  src/app/service/popup.service.ts
Labels: size/L

#129 Fix
  package-lock.json
  src/app/customer/customer.component.css
  src/app/customer/customer.component.ts
  src/app/user-detail/user-detail.component.css
  src/app/user-detail/user-detail.component.html
  src/app/welcome/redesign/TableComponent.ts
Labels: size/XL

#130 Uklonjeno cancel dugme, izmenjen izgled exchange-rate tabele, ...
  src/app/buy-popup/buy-popup.component.html
  src/app/buy-popup/buy-popup.component.ts
  src/app/exchange-rate/exchange-rate.component.css
  src/app/exchange-rate/exchange-rate.component.html
  src/app/exchange-rate/exchange-rate.component.ts
  src/app/model/exchange-rate-filter-pipe.pipe.ts
  src/app/model/forex-filter-pipe.pipe.ts
  src/app/model/model.ts
Labels: size/L

#131 Sprint 5 fix
  src/app/account-details-pop-up/account-details-pop-up.component.ts
  src/app/app.routes.ts
  src/app/change-account-name-pop-up/change-account-name-pop-up.component.html
  src/app/change-account-name-pop-up/change-account-name-pop-up.component.ts
  src/app/new-payment/new-payment.component.css
  src/app/new-payment/new-payment.component.html
  src/app/new-payment/new-payment.component.ts
  src/app/service/bank-account.service.ts
Labels: size/M

#134 Search fix
  src/app/security-list/security-list.component.ts
  src/app/service/stock.service.ts
Labels: lgtm, size/S

#135 Fix: delete user and add require approval
  src/app/add-user/add-user.component.html
  src/app/add-user/add-user.component.ts
  src/app/list-user/list-user.component.html
  src/app/list-user/list-user.component.ts
Labels: lgtm, size/S

#133 Order history i Requests tab
  src/app/app.component.html
  src/app/model/model.ts
  src/app/orders/FilterByStatusPipe.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/service/order.service.ts
Labels: size/L, lgtm

#136 various bug fixes
  src/app/add-user/add-user.component.html
  src/app/add-user/add-user.component.ts
  src/app/list-user/list-user.component.ts
  src/app/model/model.ts
  src/app/service/employee.service.ts
  src/app/service/popup.service.ts
  src/app/update-user/update-user.component.html
  src/app/update-user/update-user.component.ts
Labels: size/L

#137 Orders approve/deny, user pipe
  src/app/app.component.html
  src/app/edit-customer/edit-customer.component.html
  src/app/list-user/TransformUsersPipe.ts
  src/app/login-page/login-page.component.html
  src/app/model/model.ts
  src/app/orders/orders.component.ts
  src/app/service/future.service.ts
  src/app/service/order.service.ts
  src/app/update-user/update-user.component.html
  src/app/welcome/redesign/TransparentTextField.ts
Labels: size/M

#140 Kopirao ceo Jovicev Pr za fetch i dodao novu kolonu u tabelu securities
  src/app/add-customer/add-customer.component.css
  src/app/add-customer/add-customer.component.html
  src/app/edit-customer/edit-customer.component.css
  src/app/edit-customer/edit-customer.component.html
  src/app/edit-recipient/edit-recipient.component.ts
  src/app/model/model.ts
  src/app/new-recipient/new-recipient.component.ts
  src/app/orders/TransformSecuritiesPipe.ts
  src/app/orders/orders.component.ts
  src/app/sell-popup/sell-popup.component.ts
  src/app/service/order.service.ts
  src/app/transaction-popup/transaction-popup.component.ts
  src/app/welcome/redesign/OrangeButton.ts
  src/app/welcome/redesign/OutlineOrangeButton.ts
Labels: size/L

#141 fixed sprint5
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.ts
  src/app/list-user/TransformUsersPipe.ts
  src/app/list-user/list-user.component.ts
  src/app/service/customer.service.ts
  src/app/transform-forex.pipe.ts
  src/app/transform-future.pipe.ts
  src/app/transform-security.pipe.ts
  src/app/update-user/update-user.component.html
Labels: size/L

#146 Create OWNERS
  OWNERS
Labels: size/XS

#145 Merge fix
  package-lock.json
  package.json
  src/app/model/model.ts
  src/app/orders/orders.component.ts
  src/app/service/order.service.ts
Labels: approved, size/L, lgtm

#148 Update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm
