Repository RAF-SI-2023/Banka-1-Frontend, pull requests merged in 2024-07, with the labels that each got.

#271 Sprint 5
  src/app/app.component.html
  src/app/buy-stock-popup/buy-stock-popup.component.ts
  src/app/model/model.ts
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/orders.component.ts
  src/app/sell-popup/sell-popup.component.html
  src/app/sell-popup/sell-popup.component.ts
  src/app/service/order.service.ts
  src/app/service/popup.service.ts
Labels: approved, size/L, lgtm

#274 Sprint 5 otc
  src/app/otc/otc.component.css
  src/app/otc/otc.component.html
Labels: approved, lgtm, size/S

#272 Uklonjeni dupli Margin u sidebar-u i order history u tabeli za pravna…
  src/app/app.component.html
  src/app/orders-legal-persons/orders-legal-persons.component.html
Labels: size/M, approved, lgtm

#273 Egde cases handling
  src/app/model/model.ts
  src/app/orders/orders.component.ts
  src/app/otc-multi/otc-multi.component.html
  src/app/service/multi-otc.service.ts
Labels: approved, lgtm, size/S

#275 Multi OTC fully works
  src/app/model/model.ts
  src/app/otc-multi/otc-multi.component.html
  src/app/otc-multi/otc-multi.component.ts
  src/app/service/multi-otc.service.ts
Labels: approved, size/L, lgtm

#277 Multi OTC new feature buttons
  src/app/model/model.ts
  src/app/otc-multi/otc-multi.component.css
  src/app/otc-multi/otc-multi.component.html
  src/app/otc-multi/otc-multi.component.ts
  src/app/service/multi-otc.service.ts
Labels: size/M, approved, lgtm

#281 Cypress
  angular.json
  cypress.config.js
  cypress/e2e/employee-list/admin-employees.cy.js
  cypress/e2e/orders-tests/orders.cy.js
  cypress/e2e/payment-tests/payments.cy.js
  cypress/e2e/securities-tests/securities.cy.js
  cypress/fixtures/example.json
  cypress/screenshots/orders-tests/orders.cy.js/orders test -- should login as customer and submit invalid form (failed).png
  cypress/screenshots/payment-tests/payments.cy.js/login test -- should login as customer and add new recipient (failed).png
  cypress/screenshots/payment-tests/payments.cy.js/login test -- should login as employee (failed).png
  cypress/screenshots/securities-tests/securities.cy.js/orders test -- should login as customer and submit invalid form (failed).png
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/videos/employee-list/admin-employees.cy.js.mp4
  cypress/videos/orders-tests/orders.cy.js.mp4
  cypress/videos/payment-tests/payments.cy.js.mp4
  cypress/videos/securities-tests/securities.cy.js.mp4
  package-lock.json
  package.json
Labels: approved, lgtm

#282 Sprint 5
  cypress/e2e/employee-list/admin-employees.cy.js
  cypress/e2e/orders-tests/orders.cy.js
  cypress/e2e/payment-tests/payments.cy.js
  cypress/e2e/securities-tests/securities.cy.js
Labels: size/M, approved, lgtm

#284 Fix
  src/app/bank-account-admin/bank-account-admin.component.ts
  src/app/exchange-transaction-report/exchange-transaction-report.component.ts
  src/app/model/model.ts
  src/app/orders-legal-persons/orders-legal-persons.component.html
  src/app/orders-legal-persons/orders-legal-persons.component.ts
  src/app/orders/orders.component.html
  src/app/orders/orders.component.ts
  src/app/service/bank-account.service.ts
  src/app/service/exchange-transaction-report.service.ts
  src/app/service/legal-person.service.ts
Labels: approved, size/L, lgtm

#285 Final
  src/app/app.component.html
  src/app/exchange-transaction-report/exchange-transaction-report.component.ts
  src/app/service/exchange-transaction-report.service.ts
Labels: size/M, approved, lgtm

#286 Sprint 5
  src/app/app.component.html
Labels: approved, size/XS, lgtm

#283 Sprint 5
  .prow/frontend.yaml
  README.md
  cypress/e2e/employee-list/admin-employees.cy.js
  cypress/e2e/orders-tests/orders.cy.js
  cypress/e2e/payment-tests/payments.cy.js
  cypress/e2e/securities-tests/securities.cy.js
  package-lock.json
  package.json
Labels: size/XL, approved, lgtm

#288 Sprint 5
  README.md
Labels: approved, size/XS, lgtm

#289 Update README.md
  README.md
Labels: approved, lgtm
